### ISSUE TITLE
拼写错误？？

### ISSUE THREAD

**Issue by zzusunjs** [CavsZhouyou/Front-End-Interview-Notebook#15]
工具这一节中第四点疑似存在 拼写错误。原文如下：

> git merge 和 git rebase 都是用于分支合并，关键在 commit 记录的处理上不同。
> 
> git merge 会新建一个新的 commit 对象，然后两个分支以前的 commit 记录都指向这个新 commit 记录。这种方法会
> 保留之前每个分支的 commit 历史。
> 
> git merge 会先找到两个分支的第一个共同的 commit 祖先记录，然后将提取当前分支这之后的所有 commit 记录，然后
> 将这个 commit 记录添加到目标分支的最新提交后面。经过这个合并后，两个分支合并后的 commit 记录就变为了线性的记
> 录了。

git merge 关于commit  操作的说明有两点，没有关于git rebase 关于commit 的说明 。

**Comment by CavsZhouyou** [comment]
感谢指正，文档已经修正了。
