### ISSUE TITLE
关于假值类型那里

### ISSUE THREAD

**Issue by SHUAXINDIARY** [CavsZhouyou/Front-End-Interview-Notebook#18]
描述里说获取到dom的类数组对象强制类型转换成布尔后为false，我试了下，是true啊

**Comment by CavsZhouyou** [comment]
[document.all 测试结果](https://cavszhouyou-1254093697.cos.ap-chongqing.myqcloud.com/false.png)

**Comment by SHUAXINDIARY** [comment]
> [document.all 测试结果](https://cavszhouyou-1254093697.cos.ap-chongqing.myqcloud.com/false.png)

哎  那是我对假值对象理解错误了。我刚才又去试了试，反而有点疑惑了，那请教一下，.all不就是获取页面所有的dom嘛，为什么他和其他获取dom的操作返回的类型不一样呢。前者是undefined，后者是object，但是打印出来看着都是类数组对象呀。前者也有对象才有的__proto__呢，迷惑

**Comment by CavsZhouyou** [comment]
我的理解是，假值对象指的是常规 JavaScript 语法基础上浏览器创建的一些外来值，假值对象和正常对象没有什么不同，区别仅在于强制类型转换时会被转换为  false，这个可能是 JS 引擎内部实现导致的结果，具体原因我没有深入了解过。如果你有新的理解，欢迎指正！

**Comment by SHUAXINDIARY** [comment]
> 我的理解是，假值对象指的是常规 JavaScript 语法基础上浏览器创建的一些外来值，假值对象和正常对象没有什么不同，区别仅在于强制类型转换时会被转换为 false，这个可能是 JS 引擎内部实现导致的结果，具体原因我没有深入了解过。如果你有新的理解，欢迎指正！

好吧 谢谢 打扰您了
