### ISSUE TITLE
JavaScript的17点转换成字符串

### ISSUE THREAD

**Issue by Duota-Ni** [CavsZhouyou/Front-End-Interview-Notebook#32]
null 和 undefined 没有toString()方法
String()方法才可以将null 转换为 "null"，undefined 转换为 "undefined"

**Comment by CavsZhouyou** [comment]
你好，这里的 ToString 指的不是 toString 方法，而是指的强制类型转换这个操作。

**Comment by Duota-Ni** [comment]
噢噢，谢谢解惑
