### ISSUE TITLE
感谢总结，下面是我发现的一些小问题

### ISSUE THREAD

**Issue by zhangyunihao** [CavsZhouyou/Front-End-Interview-Notebook#48]
算法 - 希尔排序一节中提到“希尔排序的平均时间复杂度为 O(nlogn) ”是不准确的。
原因：步长序列会影响希尔排序的时间复杂度，然而还没有一种补偿能达到O(nlogn)，最快的也只有O(n(logn)^2)

**Comment by zhangyunihao** [comment]
91. 介绍一下 js 的节流与防抖？中有如下代码

1. function debounce(fn, wait) {
2.   var timer = null;
3. 
4.   return function() {
5.     var context = this,
6.       args = arguments;
7. 
8.     // 如果此时存在定时器的话，则取消之前的定时器重新记时
9.     if (timer) {
10.       clearTimeout(timer);
11.       timer = null;
12.     }
13. 
14.     // 设置定时器，使事件间隔指定事件后执行
15.     timer = setTimeout(() => {
16.       fn.apply(context, args);
17.     }, wait);
18.   };
19. }

其中第五行保存this对象是多余的，因为setTimeout第一个参数是回调函数，会自动获取this对象。

**Comment by zhangyunihao** [comment]
```
// 函数节流的实现;
function throttle(fn, delay) {
  var preTime = Date.now();

  return function() {
    var context = this,
      args = arguments,
      nowTime = Date.now();

    // 如果两次时间间隔超过了指定时间，则执行函数。
    if (nowTime - preTime >= delay) {
      preTime = Date.now();
      return fn.apply(context, args);
    }
  };
}
```

最后面的 return fn.apply(context, args)写成fn.apply(context, args)就可以了

**Comment by zhangyunihao** [comment]
96. js 中的深浅拷贝实现？
```
// 深拷贝的实现;

function deepCopy(object) {
  if (!object || typeof object !== "object") return;

  let newObject = Array.isArray(object) ? [] : {};

  for (let key in object) {
    if (object.hasOwnProperty(key)) {
      newObject[key] =
        typeof object[key] === "object" ? deepCopy(object[key]) : object[key];
    }
  }

  return newObject;
}
```
 typeof object[key] === "object"   因为有null的存在，应该改成object[key] instanceof Object

**Comment by CavsZhouyou** [comment]
> 算法 - 希尔排序一节中提到“希尔排序的平均时间复杂度为 O(nlogn) ”是不准确的。
> 原因：步长序列会影响希尔排序的时间复杂度，然而还没有一种补偿能达到O(nlogn)，最快的也只有O(n(logn)^2)

![image](https://user-images.githubusercontent.com/29836408/114299121-437a9b00-9aec-11eb-9b35-72d560d9eb80.png)

感谢指正，但我理解 O(n(logn)^2) 指的是最坏情况下的最优时间复杂度，而这里的平均时间复杂度是指的是最优和最坏情况下的一个时间负责度的平均，所以应该是没有问题的。

**Comment by CavsZhouyou** [comment]
> 1. js 中的深浅拷贝实现？
> 
> ```
> // 深拷贝的实现;
> 
> function deepCopy(object) {
>   if (!object || typeof object !== "object") return;
> 
>   let newObject = Array.isArray(object) ? [] : {};
> 
>   for (let key in object) {
>     if (object.hasOwnProperty(key)) {
>       newObject[key] =
>         typeof object[key] === "object" ? deepCopy(object[key]) : object[key];
>     }
>   }
> 
>   return newObject;
> }
> ```
> 
> typeof object[key] === "object" 因为有null的存在，应该改成object[key] instanceof Object

这里先做了 !object 的判断，所以 null 的情况不会走到 typeof object[key] === "object" 这个分支里。

**Comment by CavsZhouyou** [comment]
> 1. 介绍一下 js 的节流与防抖？中有如下代码
> 
> ```
> function debounce(fn, wait) {
> var timer = null;
> return function() {
> var context = this,
> args = arguments;
> 
> // 如果此时存在定时器的话，则取消之前的定时器重新记时
> if (timer) {
> clearTimeout(timer);
> timer = null;
> }
> 
> // 设置定时器，使事件间隔指定事件后执行
> timer = setTimeout(() => {
> fn.apply(context, args);
> }, wait);
> };
> }
> ```
> 
> 其中第五行保存this对象是多余的，因为setTimeout第一个参数是回调函数，会自动获取上下文的this对象。
> throttle函数有同样的问题，直接调用fn.apply(this, args)就好了

感谢指正，从作用上来看，这里的 context 的确是多余的一步，但当时这样写的目的，是想提醒大家这里可能涉及到的 this 指向变化问题。

**Comment by zhangyunihao** [comment]
> > 1. js 中的深浅拷贝实现？
> > 
> > ```
> > // 深拷贝的实现;
> > 
> > function deepCopy(object) {
> >   if (!object || typeof object !== "object") return;
> > 
> >   let newObject = Array.isArray(object) ? [] : {};
> > 
> >   for (let key in object) {
> >     if (object.hasOwnProperty(key)) {
> >       newObject[key] =
> >         typeof object[key] === "object" ? deepCopy(object[key]) : object[key];
> >     }
> >   }
> > 
> >   return newObject;
> > }
> > ```
> > 
> > 
> > typeof object[key] === "object" 因为有null的存在，应该改成object[key] instanceof Object
> 
> 这里先做了 !object 的判断，所以 null 的情况不会走到 typeof object[key] === "object" 这个分支里。
当某个object[key]为null的时候也会调用 deepCopy(object[key])，然而此时会返回undefined，而不是null，也是有问题的。

**Comment by zhangyunihao** [comment]
> > 1. js 中的深浅拷贝实现？
> > 
> > ```
> > // 深拷贝的实现;
> > 
> > function deepCopy(object) {
> >   if (!object || typeof object !== "object") return;
> > 
> >   let newObject = Array.isArray(object) ? [] : {};
> > 
> >   for (let key in object) {
> >     if (object.hasOwnProperty(key)) {
> >       newObject[key] =
> >         typeof object[key] === "object" ? deepCopy(object[key]) : object[key];
> >     }
> >   }
> > 
> >   return newObject;
> > }
> > ```
> > 
> > 
> > typeof object[key] === "object" 因为有null的存在，应该改成object[key] instanceof Object
> 
> 这里先做了 !object 的判断，所以 null 的情况不会走到 typeof object[key] === "object" 这个分支里。
当某个object[key]为null的时候也会调用 deepCopy(object[key])，然而此时会返回undefined，而不是null，也是有问题的。

**Comment by zhangyunihao** [comment]
> > > 1. js 中的深浅拷贝实现？
> > > 
> > > ```
> > > // 深拷贝的实现;
> > > 
> > > function deepCopy(object) {
> > >   if (!object || typeof object !== "object") return;
> > > 
> > >   let newObject = Array.isArray(object) ? [] : {};
> > > 
> > >   for (let key in object) {
> > >     if (object.hasOwnProperty(key)) {
> > >       newObject[key] =
> > >         typeof object[key] === "object" ? deepCopy(object[key]) : object[key];
> > >     }
> > >   }
> > > 
> > >   return newObject;
> > > }
> > > ```
> > > 
> > > 
> > > typeof object[key] === "object" 因为有null的存在，应该改成object[key] instanceof Object
> > 
> > 
> > 这里先做了 !object 的判断，所以 null 的情况不会走到 typeof object[key] === "object" 这个分支里。
> > 当某个object[key]为null的时候也会调用 deepCopy(object[key])，然而此时会返回undefined，而不是null，也是有问题的。

当某个object[key]为null的时候也会调用 deepCopy(object[key])，然而此时会返回undefined，而不是null，也是有问题的。

**Comment by CavsZhouyou** [comment]
> > > > 1. js 中的深浅拷贝实现？
> > > > 
> > > > ```
> > > > // 深拷贝的实现;
> > > > 
> > > > function deepCopy(object) {
> > > >   if (!object || typeof object !== "object") return;
> > > > 
> > > >   let newObject = Array.isArray(object) ? [] : {};
> > > > 
> > > >   for (let key in object) {
> > > >     if (object.hasOwnProperty(key)) {
> > > >       newObject[key] =
> > > >         typeof object[key] === "object" ? deepCopy(object[key]) : object[key];
> > > >     }
> > > >   }
> > > > 
> > > >   return newObject;
> > > > }
> > > > ```
> > > > 
> > > > 
> > > > typeof object[key] === "object" 因为有null的存在，应该改成object[key] instanceof Object
> > > 
> > > 
> > > 这里先做了 !object 的判断，所以 null 的情况不会走到 typeof object[key] === "object" 这个分支里。
> > > 当某个object[key]为null的时候也会调用 deepCopy(object[key])，然而此时会返回undefined，而不是null，也是有问题的。
> 
> 当某个object[key]为null的时候也会调用 deepCopy(object[key])，然而此时会返回undefined，而不是null，也是有问题的。

恩，的确会有这个问题，已经修正了。这里的深拷贝实现是一个最基础的版本，很多特殊情况都没有考虑，建议可以参考一下这篇文章 https://juejin.cn/post/6844903929705136141
