### ISSUE TITLE
JavaScript面试题总结的最后一题

### ISSUE THREAD

**Issue by hua03** [CavsZhouyou/Front-End-Interview-Notebook#5]
小哥，JavaScript面试题的最后一题的正则要加修饰符`i`，不然句首的字母和一些专有名词的大写字母匹配不到。

**Comment by Garfielden** [comment]
好的，但我不知道怎麼改正它


乘风 <notifications@github.com> 於 2020年3月15日 週日 下午4:30寫道：

**Comment by CavsZhouyou** [comment]
> 小哥，JavaScript面试题的最后一题的正则要加修饰符`i`，不然句首的字母和一些专有名词的大写字母匹配不到。

方法最开始对文章进行了 toLowerCase 的处理，所以这个问题是可以避免的。

**Comment by hua03** [comment]
Sorry，我忽略了这个。
