### ISSUE TITLE
非常感谢大佬分享！有个问题想请教一下

### ISSUE THREAD

**Issue by hakthiang** [CavsZhouyou/Front-End-Interview-Notebook#50]
js知识总结第一条

> js 一共有六种基本数据类型，分别是 Undefined、Null、Boolean、Number、String，还有在 ES6 中新增的 Symbol 和 ES10 中新增的 BigInt 类型。

这里应该是笔误少写了object？

**Comment by CavsZhouyou** [comment]
感谢提问，object 应该属于引用数据类型。
