### ISSUE TITLE
使用 reduce 方法实现 forEach、map、filter有误

### ISSUE THREAD

**Issue by openks** [CavsZhouyou/Front-End-Interview-Notebook#51]
[10. 使用 reduce 方法实现 forEach、map、filter](https://github.com/CavsZhouyou/Front-End-Interview-Notebook/blob/master/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95.md#10-%E4%BD%BF%E7%94%A8-reduce-%E6%96%B9%E6%B3%95%E5%AE%9E%E7%8E%B0-foreachmapfilter)
```js
 function forEachUseReduce(array, handler) {
   array.reduce(function (pre, item, index) {
     handler(item, index);
   },null);// 这里少了初始化参数，如果没有初始化参数数组里的第一个会当做初始化参数导致数组第一个直接被忽略
 }
 forEachUseReduce([1,2,3],(ele)=>{console.log(ele)}) // 按文章里的写法这里只会出现2，3
```
[详见MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)

**Comment by CavsZhouyou** [comment]
![image](https://user-images.githubusercontent.com/29836408/117128936-a3552080-add0-11eb-85aa-4f7da0cfd50d.png)
感谢指正，但是这里正是为了避免这个问题，所以才将 initialValue 设置为了 null。

**Comment by openks** [comment]
我看文章里并没有将 initialValue 设置为了 null，我贴的代码里是我加过的

**Comment by CavsZhouyou** [comment]
已修改
