### ISSUE TITLE
感谢大佬分享，javascript53---疑问

### ISSUE THREAD

**Issue by openks** [CavsZhouyou/Front-End-Interview-Notebook#53]
谢谢大佬贡献资料，感觉这里有点困惑，

[javascript53](https://github.com/CavsZhouyou/Front-End-Interview-Notebook/blob/master/JavaScript/JavaScript.md#53-foreachcallfunctionaastyleoutline1px-solid-mathrandom124tostring16-%E8%83%BD%E8%A7%A3%E9%87%8A%E4%B8%80%E4%B8%8B%E8%BF%99%E6%AE%B5%E4%BB%A3%E7%A0%81%E7%9A%84%E6%84%8F%E6%80%9D%E5%90%97)
`[].forEach.call($$(""),function(a){a.style.outline="1px solid #"+(~~(Math.random()(1<<24))).toString(16)}) `

这里的代码展示不全，没看懂，放到控制台执行直接报错, 后来根据下面的分析发现少了两个星号。

`[].forEach.call($$("*"),function(a){a.style.outline="1px solid #"+(~~(Math.random()*(1<<24))).toString(16)}) `

发现二级三级标题都可以用单行code的格式，链接好像不行

**Comment by CavsZhouyou** [comment]
感谢指正，已经修改了！
