### ISSUE TITLE
7. null 和 undefined 的区别

### ISSUE THREAD

**Issue by xiaolannuoyi** [CavsZhouyou/Front-End-Interview-Notebook#55]
可以加一条，转换成数字，`+null` 输出 0 ，`+undefined`输出NaN

**Comment by CavsZhouyou** [comment]
这里更多介绍的是两者定义上的区别，强制转换时的不同在 [这里](https://github.com/CavsZhouyou/Front-End-Interview-Notebook/blob/master/JavaScript/JavaScript.md#18-%E5%85%B6%E4%BB%96%E5%80%BC%E5%88%B0%E6%95%B0%E5%AD%97%E5%80%BC%E7%9A%84%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99) 有提到。
